name: Release
on:
  push:
    tags: ["v*"]

permissions:
  contents: write
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest  # Key change
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: sudo dpkg --add-architecture i386
      - run: sudo apt-get update
      - run: sudo apt-get install -y wine64 wine32
      - run: npm run build
      - run: npx electron-builder build --win --linux --publish always